title: Somebody's Blog! # name of the site
author: somebody # name of site's author
email: confermaeta02@gmail.com # email of site's author
url: https://jNSFZbpdjdwzbVTwKNsH.github.io # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Uno stralcio della vita e dei pensieri di qualcuno, 
  dal suo punto di vista

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "<--" # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  pagina:
    output: true

  pensiero:
    output: true

  poesia:
    output: true

  riflessione:
    output: true

  libro:
    output: true

  estina:
    output: true

  monica:
    output: true

  weav:
    output: true

  modella:
    output: true

  lettera:
    output: true
