name: Convert Markdown to HTML
on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  convert-markdown:
    runs-on: ubuntu-latest
    steps:
      # Checkout your main repository (where markdown files are)
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Checkout the rossoc.github.io repository (where the program is)
      - name: Checkout markdown converter
        uses: actions/checkout@v4
        with:
          repository: rossoc/rossoc.github.io
          path: converter

      # Install Rust toolchain
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      # Convert all markdown files in the main repository
      - name: Convert markdown files to HTML
        run: |
          cd converter
          cargo run -- -s ../ -o ./_site

      # Commit and push generated HTML files
      - name: Commit HTML files
        run: |
          git config --local user.email "github-action@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add *.html **/*.html  # Add all generated HTML files
          git commit -m "Auto-convert markdown to HTML [skip ci]"
          git push